//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Exams = new HashSet<Exams>();
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
    
        public virtual ICollection<Exams> Exams { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
