//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Pressure { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<int> HealthGroupId { get; set; }
        public Nullable<bool> IsFit { get; set; }
        public Nullable<System.DateTime> NextExamDate { get; set; }
    
        public virtual HealthGroups HealthGroups { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
