//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<byte> IsBlocked { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
